In [209]:
import numpy as np

In [210]:
def parse_input(is_test=True):
    file_name = "input-test.txt" if is_test else "input.txt"

    tmp = list()
    with open(file_name, "r") as file:
        for line in file:
            tmp_line = line.strip().split()
            if len(tmp_line) == 0:
                continue

            if tmp_line[0] == "Button":
                tmp.append([int(tmp_line[-2][:-1].split("+")[-1]), int(tmp_line[-1].split("+")[-1])])
            else:
                tmp.append([int(tmp_line[-2][:-1].split("=")[-1]), int(tmp_line[-1].split("=")[-1])])

    result = list([(tmp[i : i + 3]) for i in range(0, len(tmp), 3)])
    return result

In [211]:
def solve_linear_equation(linear_equation: list) -> np.ndarray:
    a = np.array([linear_equation[i] for i in range(len(linear_equation) - 1)])
    a_t = a.transpose()
    b = np.array(linear_equation[-1])

    result = np.array([np.int64(ans) for ans in np.linalg.solve(a_t, b).tolist()])

    if np.allclose(np.dot(a_t, result), b):
        print(a_t, b, result)
        return result
    else:
        return None

In [212]:
def is_exceeds_button_pressed_limit(button_pressed: np.ndarray, limit: int) -> bool:
    for count in button_pressed:
        if count > limit:
            return True

    return False

In [213]:
def get_no_token_use(button_pressed: np.ndarray, token_usage: np.ndarray):
    return np.vdot(button_pressed, token_usage)

In [214]:
def solve_part_1():
    inputs = parse_input(is_test=False)

    result = np.int64(0)
    for linear_equation in inputs:
        button_pressed = solve_linear_equation(linear_equation)

        if button_pressed is None:
            continue

        if is_exceeds_button_pressed_limit(button_pressed, 100):
            continue

        print(get_no_token_use(button_pressed, np.array([3, 1])), "\n=====\n")
        result += get_no_token_use(button_pressed, np.array([3, 1]))

    return int(result)

In [215]:
solve_part_1()

[[83 34]
 [59 99]] [4485 8127] [27 66]
147 
=====

[[18 83]
 [60 58]] [ 9765 10902] [86 99]
357 
=====

[[64 12]
 [24 23]] [3912 2466] [51 54]
207 
=====

[[92 37]
 [42 81]] [9380 8898] [73 72]
291 
=====

[[69 18]
 [41 71]] [4197 7077] [41 76]
199 
=====

[[16 71]
 [69 62]] [3327 8243] [97 25]
316 
=====

[[86 28]
 [12 44]] [9118 4600] [79 83]
320 
=====

[[20 41]
 [39 14]] [4755 4326] [84 75]
327 
=====

[[20 93]
 [78 58]] [4373 4562] [28 41]
125 
=====

[[27 50]
 [70 21]] [5823 8253] [99 63]
360 
=====

[[88 70]
 [28 79]] [8992 5584] [64 48]
240 
=====

[[94 70]
 [12 96]] [8188 3396] [67 27]
228 
=====

[[42 78]
 [48 21]] [7482 5280] [89 48]
315 
=====

[[34 91]
 [78 67]] [6544 8208] [64 48]
240 
=====

[[42 27]
 [61 11]] [3246 3868] [58 30]
204 
=====

[[82 24]
 [18 94]] [8468 3456] [98 18]
312 
=====

[[22 47]
 [79 39]] [4634 6518] [44 78]
210 
=====

[[50 96]
 [69 39]] [2720 1884] [16 20]
68 
=====

[[55 78]
 [62 22]] [7064 3480] [32 68]
164 
=====

[[68 22]
 [30 48]] [3872 3240]

27833

In [216]:
# 27833 too low